name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CMAKE_GENERATOR: Ninja
  SCE_ROOT_DIR: ${{ github.workspace }}/ci-base/SCE
  SCE_PSP2_SDK_DIR: ${{ github.workspace }}/ci-base/sdk
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: get-cmake
      uses: lukka/get-cmake@v3.20.1
      
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Checkout CI base
      uses: actions/checkout@v2
      with:
          repository: SonicMastr/ci-base
          path: ci-base
          token: ${{ secrets.CI_TOKEN }}
          
    - name: Create Install Prefix
      run: |
          mkdir ${{github.workspace}}/sdk
          mkdir ${{github.workspace}}/sdk/target
          
    - name: Install VDSuite
      run: |
          $ProgressPreference = "SilentlyContinue"
          "psp2-cmake-toolchains","cmake-modules","toolchain","libraries"
            | ForEach-Object {
                $base_path = "https://bin.shotatoshounenwachigau.moe/vdsuite"
                Invoke-WebRequest -Uri "$base_path/vdsuite-$_-latest.zip" -OutFile "$_.zip"
                Expand-Archive -Path "$_.zip" -DestinationPath ${{ github.workspace }}/ci-base
              }
          pip install lxml

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_INSTALL_PREFIX=sdk/target -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_TOOLCHAIN_FILE:FILEPATH=${{ env.SCE_PSP2_SDK_DIR }}/host_tools/build/cmake/psp2-snc-toolchain.cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
         cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target install -j ${{ env.NUMBER_OF_PROCESSORS }}
        
    - name: Archive
      run: |
          7z a ${{ github.workspace }}/PIB-VDSuite-AutoBuild.zip ${{ github.workspace }}/sdk
          if ($LastExitCode -ne 0) { exit $LastExitCode }
    
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: PIB-VDSuite-AutoBuild
        path: ${{ github.workspace }}/PIB-VDSuite-AutoBuild.zip
          
      
